language: php

php:
  - '8.2'
  - nightly
  
before_script:
  - composer require php-coveralls/php-coveralls
  - composer install
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - travis_retry php vendor/bin/coveralls -v
